services:
  chatterbox-tts:
    build:
      context: https://github.com/devnen/Chatterbox-TTS-Server.git
      dockerfile: Dockerfile.cpu
    container_name: chatterbox-tts
    restart: unless-stopped
    ports:
      - "8004:8004"
    volumes:
      - chatterbox_voices:/app/voices
      - chatterbox_reference_audio:/app/reference_audio
      - chatterbox_outputs:/app/outputs
      - chatterbox_logs:/app/logs
      - chatterbox_hf_cache:/app/hf_cache
    environment:
      HF_HUB_ENABLE_HF_TRANSFER: "1"

volumes:
  chatterbox_voices:
  chatterbox_reference_audio:
  chatterbox_outputs:
  chatterbox_logs:
  chatterbox_hf_cache:
